baseURL = "https://eric.hripko.com/"
languageCode = "en-gb"
title = "Eric Hripko2"
theme= "artisan"
canonifyURLs = true
enableRobotsTXT = true

[permalinks]
    posts = "/:year/:month/:day/:title/"

[menu]

[[menu.main]]
identifier = "history"
name = "History"
url = "/posts/"

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"

[params]
# General
avatar = "/assets/avatar.jpeg"
subtitle = "Software Engineer"
description = """
I have always thought of coding as art and a form of self-expression. Having
picked this hobby up in school, I have now turned it into my profession. My
specialty is modern web and container infrastructure. Currently, I work
primarily with Python, Go and Docker. In this blog, I document adventures
encountered during coding for open source and pet projects.
"""
analytics = "UA-119124355-1"

# Social
disqus = "eric-hripko"
github = "EricHripko"
linkedin = "eric-hripko"
S00px = "eric-hripko"

# Employment
work = "Bloomberg L.P."
university = "University of Leeds"
location= "London, UK"
